/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MoonPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  serverUrl: "http://localhost:3000",
  // Default all planets to enabled
  enableSun: true,
  enableMoon: true,
  enableMercury: true,
  enableVenus: true,
  enableMars: true,
  enableJupiter: true,
  enableSaturn: true,
  enableUranus: true,
  enableNeptune: true,
  enablePluto: true,
  // Default major aspects to enabled, minor aspects to disabled
  enableConjunction: true,
  enableOpposition: true,
  enableTrine: true,
  enableSquare: true,
  enableSextile: true,
  enableQuincunx: false,
  enableSemiSextile: false,
  enableSemiSquare: false,
  enableSesquiquadrate: false,
  enableQuintile: false
};
var MoonPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.api = {
      getMoonData: this.getMoonData.bind(this),
      getMoonPhaseEmoji: this.getMoonPhaseEmoji.bind(this),
      getWeeklyMajorPhase: this.getWeeklyMajorPhase.bind(this),
      getPlanetaryData: this.getPlanetaryData.bind(this),
      getPlanetGlyph: this.getPlanetGlyph.bind(this),
      getAspectsData: this.getAspectsData.bind(this)
    };
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new MoonSettingTab(this.app, this));
    this.addCommand({
      id: "current-moon-phase",
      name: "Current Moon Phase",
      editorCallback: (editor, view) => {
        this.getMoonData().then((moonData) => {
          const moonEmoji = this.getMoonPhaseEmoji(moonData.moonPhase);
          editor.replaceSelection(`${moonEmoji} ${moonData.moonSign}`);
        }).catch((error) => {
          console.error("Error fetching moon data:", error);
          editor.replaceSelection("Error fetching moon data. Check console for details.");
        });
      }
    });
    this.addCommand({
      id: "current-moon-degree",
      name: "Current Moon Degree",
      editorCallback: (editor, view) => {
        this.getMoonData().then((moonData) => {
          const moonEmoji = this.getMoonPhaseEmoji(moonData.moonPhase);
          editor.replaceSelection(`${moonEmoji} ${moonData.moonSign} ${moonData.degreeInSign}\u02DA`);
        }).catch((error) => {
          console.error("Error fetching moon data:", error);
          editor.replaceSelection("Error fetching moon data. Check console for details.");
        });
      }
    });
    this.addCommand({
      id: "weekly-phase",
      name: "Weekly Phase",
      editorCallback: (editor, view) => {
        this.getWeeklyMajorPhase().then((phase) => {
          if (!phase) {
            editor.replaceSelection("No major moon phase this week.");
            return;
          }
          const moonEmoji = this.getMoonPhaseEmoji(phase.moonPhase);
          editor.replaceSelection(`${moonEmoji} ${phase.moonSign}`);
        }).catch((error) => {
          console.error("Error fetching weekly moon phase:", error);
          editor.replaceSelection("Error fetching weekly moon phase. Check console for details.");
        });
      }
    });
    this.addCommand({
      id: "planetary-positions",
      name: "All Planetary Positions",
      editorCallback: (editor, view) => {
        this.getPlanetaryData().then((data) => {
          let output = "";
          data.planets.forEach((planet) => {
            const glyph = this.getPlanetGlyph(planet.name);
            const retroMark = planet.isRetrograde ? " \u211E" : "";
            output += `${glyph} ${planet.sign} ${planet.degreeInSign}\u02DA${retroMark}
`;
          });
          editor.replaceSelection(output.trim());
        }).catch((error) => {
          console.error("Error fetching planetary data:", error);
          editor.replaceSelection("Error fetching planetary data. Check console for details.");
        });
      }
    });
    const planets = ["Sun", "Moon", "Mercury", "Venus", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto"];
    planets.forEach((planetName) => {
      this.addCommand({
        id: `${planetName.toLowerCase()}-position`,
        name: `${planetName} Position`,
        editorCallback: (editor, view) => {
          this.getPlanetaryData().then((data) => {
            const planet = data.planets.find((p) => p.name === planetName);
            if (planet) {
              const glyph = this.getPlanetGlyph(planet.name);
              const retroMark = planet.isRetrograde ? " \u211E" : "";
              editor.replaceSelection(`${glyph} ${planet.sign} ${planet.degreeInSign}\u02DA${retroMark}`);
            } else {
              editor.replaceSelection(`Error: ${planetName} data not found`);
            }
          }).catch((error) => {
            console.error(`Error fetching ${planetName} data:`, error);
            editor.replaceSelection(`Error fetching ${planetName} data. Check console for details.`);
          });
        }
      });
    });
    this.addCommand({
      id: "all-aspects",
      name: "All Current Aspects",
      editorCallback: (editor, view) => {
        this.getAspectsData().then((data) => {
          if (data.aspects.length === 0) {
            editor.replaceSelection("No significant aspects currently.");
            return;
          }
          let output = "";
          data.aspects.forEach((aspect) => {
            const planet1Glyph = this.getPlanetGlyph(aspect.planet1);
            const planet2Glyph = this.getPlanetGlyph(aspect.planet2);
            const retrograde1 = aspect.planet1Retrograde ? " \u211E" : "";
            const retrograde2 = aspect.planet2Retrograde ? " \u211E" : "";
            output += `${planet1Glyph}${retrograde1} ${aspect.aspectSymbol} ${planet2Glyph}${retrograde2}
`;
          });
          editor.replaceSelection(output.trim());
        }).catch((error) => {
          console.error("Error fetching aspects data:", error);
          editor.replaceSelection("Error fetching aspects data. Check console for details.");
        });
      }
    });
    const planetsForAspects = ["Sun", "Moon", "Mercury", "Venus", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto"];
    planetsForAspects.forEach((planetName) => {
      this.addCommand({
        id: `${planetName.toLowerCase()}-aspects`,
        name: `${planetName} Aspects`,
        editorCallback: (editor, view) => {
          this.getAspectsData().then((data) => {
            const relevantAspects = data.aspects.filter(
              (aspect) => aspect.planet1 === planetName || aspect.planet2 === planetName
            );
            if (relevantAspects.length === 0) {
              editor.replaceSelection(`No significant aspects for ${planetName} currently.`);
              return;
            }
            let output = "";
            relevantAspects.forEach((aspect) => {
              let planet1, planet2, retrograde1, retrograde2, planet1Glyph, planet2Glyph;
              if (aspect.planet1 === planetName) {
                planet1 = aspect.planet1;
                planet2 = aspect.planet2;
                retrograde1 = aspect.planet1Retrograde ? " \u211E" : "";
                retrograde2 = aspect.planet2Retrograde ? " \u211E" : "";
              } else {
                planet1 = aspect.planet2;
                planet2 = aspect.planet1;
                retrograde1 = aspect.planet2Retrograde ? " \u211E" : "";
                retrograde2 = aspect.planet1Retrograde ? " \u211E" : "";
              }
              planet1Glyph = this.getPlanetGlyph(planet1);
              planet2Glyph = this.getPlanetGlyph(planet2);
              output += `${planet1Glyph}${retrograde1} ${aspect.aspectSymbol} ${planet2Glyph}${retrograde2}
`;
            });
            editor.replaceSelection(output.trim());
          }).catch((error) => {
            console.error(`Error fetching ${planetName} aspects:`, error);
            editor.replaceSelection(`Error fetching ${planetName} aspects. Check console for details.`);
          });
        }
      });
    });
    const aspectTypes = ["Conjunction", "Opposition", "Trine", "Square", "Sextile"];
    aspectTypes.forEach((aspectName) => {
      this.addCommand({
        id: `${aspectName.toLowerCase()}-aspects`,
        name: `${aspectName} Aspects`,
        editorCallback: (editor, view) => {
          this.getAspectsData().then((data) => {
            const relevantAspects = data.aspects.filter(
              (aspect) => aspect.aspectName === aspectName
            );
            if (relevantAspects.length === 0) {
              editor.replaceSelection(`No ${aspectName} aspects currently.`);
              return;
            }
            let output = "";
            relevantAspects.forEach((aspect) => {
              const planet1Glyph = this.getPlanetGlyph(aspect.planet1);
              const planet2Glyph = this.getPlanetGlyph(aspect.planet2);
              const retrograde1 = aspect.planet1Retrograde ? " \u211E" : "";
              const retrograde2 = aspect.planet2Retrograde ? " \u211E" : "";
              output += `${planet1Glyph}${retrograde1} ${aspect.aspectSymbol} ${planet2Glyph}${retrograde2}
`;
            });
            editor.replaceSelection(output.trim());
          }).catch((error) => {
            console.error(`Error fetching ${aspectName} aspects:`, error);
            editor.replaceSelection(`Error fetching ${aspectName} aspects. Check console for details.`);
          });
        }
      });
    });
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // Function to get moon data from the server
  async getMoonData() {
    const response = await fetch(`${this.settings.serverUrl}/moon-now`);
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    const data = await response.json();
    return data;
  }
  async getPlanetaryData() {
    const response = await fetch(`${this.settings.serverUrl}/planets-now`);
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    const data = await response.json();
    const filteredPlanets = data.planets.filter(
      (planet) => this.isPlanetEnabled(planet.name)
    );
    return {
      localEasternTime: data.localEasternTime,
      planets: filteredPlanets
    };
  }
  async getAspectsData() {
    const response = await fetch(`${this.settings.serverUrl}/aspects-now`);
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    const data = await response.json();
    const filteredAspects = data.aspects.filter((aspect) => {
      const planet1Enabled = this.isPlanetEnabled(aspect.planet1);
      const planet2Enabled = this.isPlanetEnabled(aspect.planet2);
      const aspectEnabled = this.isAspectEnabled(aspect.aspectName);
      return planet1Enabled && planet2Enabled && aspectEnabled;
    });
    return {
      localEasternTime: data.localEasternTime,
      aspects: filteredAspects
    };
  }
  // Add these new helper methods right after getAspectsData()
  isPlanetEnabled(planetName) {
    switch (planetName) {
      case "Sun":
        return this.settings.enableSun;
      case "Moon":
        return this.settings.enableMoon;
      case "Mercury":
        return this.settings.enableMercury;
      case "Venus":
        return this.settings.enableVenus;
      case "Mars":
        return this.settings.enableMars;
      case "Jupiter":
        return this.settings.enableJupiter;
      case "Saturn":
        return this.settings.enableSaturn;
      case "Uranus":
        return this.settings.enableUranus;
      case "Neptune":
        return this.settings.enableNeptune;
      case "Pluto":
        return this.settings.enablePluto;
      default:
        return false;
    }
  }
  isAspectEnabled(aspectName) {
    switch (aspectName) {
      case "Conjunction":
        return this.settings.enableConjunction;
      case "Opposition":
        return this.settings.enableOpposition;
      case "Trine":
        return this.settings.enableTrine;
      case "Square":
        return this.settings.enableSquare;
      case "Sextile":
        return this.settings.enableSextile;
      case "Quincunx":
        return this.settings.enableQuincunx;
      case "Semi-sextile":
        return this.settings.enableSemiSextile;
      case "Semi-square":
        return this.settings.enableSemiSquare;
      case "Sesquiquadrate":
        return this.settings.enableSesquiquadrate;
      case "Quintile":
        return this.settings.enableQuintile;
      default:
        return false;
    }
  }
  // Function to map moon phase to emoji
  getMoonPhaseEmoji(phase) {
    switch (phase) {
      case "New Moon":
        return "\u{1F311}";
      case "Waxing Crescent":
        return "\u{1F312}";
      case "First Quarter":
        return "\u{1F313}";
      case "Waxing Gibbous":
        return "\u{1F314}";
      case "Full Moon":
        return "\u{1F315}";
      case "Waning Gibbous":
        return "\u{1F316}";
      case "Last Quarter":
        return "\u{1F317}";
      case "Waning Crescent":
        return "\u{1F318}";
      default:
        return "\u{1F319}";
    }
  }
  // Function to map planet name to astrological glyph
  getPlanetGlyph(planetName) {
    switch (planetName) {
      case "Sun":
        return "\u2609";
      case "Moon":
        return "\u263D";
      case "Mercury":
        return "\u263F";
      case "Venus":
        return "\u2640";
      case "Mars":
        return "\u2642";
      case "Jupiter":
        return "\u2643";
      case "Saturn":
        return "\u2644";
      case "Uranus":
        return "\u2645";
      case "Neptune":
        return "\u2646";
      case "Pluto":
        return "\u2647";
      default:
        return "\u2605";
    }
  }
  // Function to get the Monday of the current week
  getMonday(d) {
    const date = new Date(d);
    const day = date.getDay();
    const diff = date.getDate() - day + (day === 0 ? -6 : 1);
    return new Date(date.setDate(diff));
  }
  // Function to format date as YYYY-MM-DD
  formatDate(date) {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, "0");
    const day = String(date.getDate()).padStart(2, "0");
    return `${year}-${month}-${day}`;
  }
  // Function to get major moon phases for the current week
  async getWeeklyMajorPhase() {
    try {
      const response = await fetch(`${this.settings.serverUrl}/weekly-major-phase`);
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      const data = await response.json();
      if (data.moonPhase) {
        return {
          date: data.date,
          moonPhase: data.moonPhase,
          moonSign: data.moonSign
        };
      }
      return null;
    } catch (error) {
      console.error("Error fetching weekly moon phase:", error);
      return null;
    }
  }
};
var MoonSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Moon Phase Settings" });
    new import_obsidian.Setting(containerEl).setName("Server URL").setDesc("URL to the moon data server (including protocol, no trailing slash)").addText((text) => text.setPlaceholder("http://localhost:3000").setValue(this.plugin.settings.serverUrl).onChange(async (value) => {
      this.plugin.settings.serverUrl = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Planets" });
    containerEl.createEl("p", { text: "Select which planets to include in calculations" });
    new import_obsidian.Setting(containerEl).setName("Sun").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableSun).onChange(async (value) => {
      this.plugin.settings.enableSun = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Moon").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableMoon).onChange(async (value) => {
      this.plugin.settings.enableMoon = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Mercury").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableMercury).onChange(async (value) => {
      this.plugin.settings.enableMercury = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Venus").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableVenus).onChange(async (value) => {
      this.plugin.settings.enableVenus = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Mars").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableMars).onChange(async (value) => {
      this.plugin.settings.enableMars = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Jupiter").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableJupiter).onChange(async (value) => {
      this.plugin.settings.enableJupiter = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Saturn").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableSaturn).onChange(async (value) => {
      this.plugin.settings.enableSaturn = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Uranus").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableUranus).onChange(async (value) => {
      this.plugin.settings.enableUranus = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Neptune").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableNeptune).onChange(async (value) => {
      this.plugin.settings.enableNeptune = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Pluto").addToggle((toggle) => toggle.setValue(this.plugin.settings.enablePluto).onChange(async (value) => {
      this.plugin.settings.enablePluto = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Aspects" });
    containerEl.createEl("p", { text: "Select which aspects to include in calculations" });
    new import_obsidian.Setting(containerEl).setName("Conjunction (\u260C)").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableConjunction).onChange(async (value) => {
      this.plugin.settings.enableConjunction = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Opposition (\u260D)").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableOpposition).onChange(async (value) => {
      this.plugin.settings.enableOpposition = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Trine (\u25B3)").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableTrine).onChange(async (value) => {
      this.plugin.settings.enableTrine = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Square (\u25A1)").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableSquare).onChange(async (value) => {
      this.plugin.settings.enableSquare = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Sextile (\u26B9)").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableSextile).onChange(async (value) => {
      this.plugin.settings.enableSextile = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Quincunx (\u26BB)").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableQuincunx).onChange(async (value) => {
      this.plugin.settings.enableQuincunx = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Semi-sextile (\u26BA)").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableSemiSextile).onChange(async (value) => {
      this.plugin.settings.enableSemiSextile = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Semi-square (\u26BC)").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableSemiSquare).onChange(async (value) => {
      this.plugin.settings.enableSemiSquare = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Sesquiquadrate (\u26BF)").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableSesquiquadrate).onChange(async (value) => {
      this.plugin.settings.enableSesquiquadrate = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Quintile (Q)").addToggle((toggle) => toggle.setValue(this.plugin.settings.enableQuintile).onChange(async (value) => {
      this.plugin.settings.enableQuintile = value;
      await this.plugin.saveSettings();
    }));
  }
};
