/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MoonPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/types.ts
var PLANETS = [
  "Sun",
  "Moon",
  "Mercury",
  "Venus",
  "Mars",
  "Jupiter",
  "Saturn",
  "Uranus",
  "Neptune",
  "Pluto"
];
var ASPECTS = [
  "Conjunction",
  "Opposition",
  "Trine",
  "Square",
  "Sextile",
  "Quincunx",
  "Semi-sextile",
  "Semi-square",
  "Sesquiquadrate",
  "Quintile"
];
var ASPECT_SYMBOLS = {
  "Conjunction": "\u260C",
  "Opposition": "\u260D",
  "Trine": "\u25B3",
  "Square": "\u25A1",
  "Sextile": "\u26B9",
  "Quincunx": "\u26BB",
  "Semi-sextile": "\u26BA",
  "Semi-square": "\u26BC",
  "Sesquiquadrate": "\u26BF",
  "Quintile": "Q"
};
var PLANET_GLYPHS = {
  Sun: "\u2609",
  Moon: "\u263D",
  Mercury: "\u263F",
  Venus: "\u2640",
  Mars: "\u2642",
  Jupiter: "\u2643",
  Saturn: "\u2644",
  Uranus: "\u2645",
  Neptune: "\u2646",
  Pluto: "\u2647",
  "North Node": "\u260A",
  "South Node": "\u260B",
  Chiron: "\u26B7",
  Ascendant: "ASC",
  Midheaven: "MC"
};
var MOON_PHASE_EMOJI = {
  "New Moon": "\u{1F311}",
  "Waxing Crescent": "\u{1F312}",
  "First Quarter": "\u{1F313}",
  "Waxing Gibbous": "\u{1F314}",
  "Full Moon": "\u{1F315}",
  "Waning Gibbous": "\u{1F316}",
  "Last Quarter": "\u{1F317}",
  "Waning Crescent": "\u{1F318}"
};
var DEFAULT_SETTINGS = {
  serverUrl: "http://localhost:3000",
  selectedChart: "",
  useNatalChart: false,
  majorOnly: true,
  natalOrb: 8,
  planets: {
    Sun: true,
    Moon: true,
    Mercury: true,
    Venus: true,
    Mars: true,
    Jupiter: true,
    Saturn: true,
    Uranus: true,
    Neptune: true,
    Pluto: true
  },
  aspects: {
    Conjunction: true,
    Opposition: true,
    Trine: true,
    Square: true,
    Sextile: true,
    Quincunx: false,
    "Semi-sextile": false,
    "Semi-square": false,
    Sesquiquadrate: false,
    Quintile: false
  },
  techniques: {
    ki: true,
    hexagram: true,
    midpoints: false,
    eclipses: false,
    dashas: false
  },
  midpointOrb: 2,
  eclipseLookaheadMonths: 12,
  birthDate: ""
};

// src/pure.ts
function normalizeBaseUrl(url) {
  return (url || "").trim().replace(/\/+$/, "");
}
function joinUrl(base, path) {
  const b = normalizeBaseUrl(base);
  const p = "/" + (path || "").replace(/^\/+/, "");
  return b + p;
}
function migrateSettings(raw) {
  if (!raw || typeof raw !== "object")
    return { ...DEFAULT_SETTINGS };
  const looksV2 = raw.planets || raw.aspects || raw.selectedChart !== void 0;
  if (looksV2) {
    return {
      ...DEFAULT_SETTINGS,
      ...raw,
      planets: { ...DEFAULT_SETTINGS.planets, ...raw.planets || {} },
      aspects: { ...DEFAULT_SETTINGS.aspects, ...raw.aspects || {} },
      techniques: { ...DEFAULT_SETTINGS.techniques, ...raw.techniques || {} }
    };
  }
  const planetMap = {
    enableSun: "Sun",
    enableMoon: "Moon",
    enableMercury: "Mercury",
    enableVenus: "Venus",
    enableMars: "Mars",
    enableJupiter: "Jupiter",
    enableSaturn: "Saturn",
    enableUranus: "Uranus",
    enableNeptune: "Neptune",
    enablePluto: "Pluto"
  };
  const aspectMap = {
    enableConjunction: "Conjunction",
    enableOpposition: "Opposition",
    enableTrine: "Trine",
    enableSquare: "Square",
    enableSextile: "Sextile",
    enableQuincunx: "Quincunx",
    enableSemiSextile: "Semi-sextile",
    enableSemiSquare: "Semi-square",
    enableSesquiquadrate: "Sesquiquadrate",
    enableQuintile: "Quintile"
  };
  const planets = { ...DEFAULT_SETTINGS.planets };
  for (const [k, v] of Object.entries(planetMap)) {
    if (typeof raw[k] === "boolean")
      planets[v] = raw[k];
  }
  const aspects = { ...DEFAULT_SETTINGS.aspects };
  for (const [k, v] of Object.entries(aspectMap)) {
    if (typeof raw[k] === "boolean")
      aspects[v] = raw[k];
  }
  return {
    ...DEFAULT_SETTINGS,
    serverUrl: typeof raw.serverUrl === "string" ? raw.serverUrl : DEFAULT_SETTINGS.serverUrl,
    planets,
    aspects
  };
}
function enabledPlanetNames(settings) {
  return PLANETS.filter((p) => settings.planets[p]);
}
function enabledAspectNames(settings) {
  return ASPECTS.filter((a) => settings.aspects[a]);
}
function filterSkyAspects(aspects, settings) {
  const enabledPlanets = new Set(enabledPlanetNames(settings));
  const enabledAspects = new Set(enabledAspectNames(settings));
  return aspects.filter((a) => enabledPlanets.has(a.planet1) && enabledPlanets.has(a.planet2) && enabledAspects.has(a.aspectName));
}
var NATAL_ASPECT_MAP = {
  "conjunction": "Conjunction",
  "opposition": "Opposition",
  "trine": "Trine",
  "square": "Square",
  "sextile": "Sextile",
  "quincunx": "Quincunx",
  "semi-sextile": "Semi-sextile",
  "semisextile": "Semi-sextile",
  "semi-square": "Semi-square",
  "semisquare": "Semi-square",
  "sesquiquadrate": "Sesquiquadrate",
  "quintile": "Quintile"
};
function natalAspectName(raw) {
  var _a;
  if (!raw)
    return null;
  return (_a = NATAL_ASPECT_MAP[raw.toLowerCase()]) != null ? _a : null;
}
function natalTransitToSkyAspect(t) {
  var _a, _b;
  const aspectName = natalAspectName(t.aspect);
  if (!aspectName)
    return null;
  const natalLabel = (_b = (_a = t.natal.planet) != null ? _a : t.natal.point) != null ? _b : "Natal";
  return {
    planet1: t.transit.planet,
    planet2: natalLabel,
    aspectName,
    aspectSymbol: t.symbol || ASPECT_SYMBOLS[aspectName],
    exactAngle: "",
    orb: t.orb,
    planet1Sign: t.transit.sign,
    planet2Sign: t.natal.sign,
    planet1Retrograde: !!t.transit.isRetrograde,
    planet2Retrograde: false
  };
}
function filterNatalTransits(transits, settings) {
  const enabledPlanets = new Set(enabledPlanetNames(settings));
  const enabledAspects = new Set(enabledAspectNames(settings));
  const out = [];
  for (const t of transits) {
    if (!enabledPlanets.has(t.transit.planet))
      continue;
    const mapped = natalTransitToSkyAspect(t);
    if (!mapped)
      continue;
    if (!enabledAspects.has(mapped.aspectName))
      continue;
    out.push(mapped);
  }
  return out;
}
function natalTransitQuery(settings) {
  const params = new URLSearchParams();
  if (settings.majorOnly)
    params.set("major", "true");
  if (Number.isFinite(settings.natalOrb))
    params.set("orb", String(settings.natalOrb));
  const qs = params.toString();
  return qs ? `?${qs}` : "";
}
function buildGenerateChartBody(input) {
  if (!input.name)
    throw new Error("Chart name is required");
  if (!input.date)
    throw new Error("Birth date is required");
  if (!input.time)
    throw new Error("Birth time is required");
  const [y, m, d] = input.date.split("-").map(Number);
  const [hh, mm] = input.time.split(":").map(Number);
  if (![y, m, d, hh, mm].every(Number.isFinite)) {
    throw new Error("Invalid date or time");
  }
  return {
    name: input.name,
    year: y,
    month: m,
    day: d,
    hour: hh,
    minute: mm,
    latitude: input.latitude,
    longitude: input.longitude,
    timezone: input.timezone,
    save: input.save !== false
  };
}
function moonPhaseEmoji(phase) {
  var _a;
  return (_a = MOON_PHASE_EMOJI[phase]) != null ? _a : "\u{1F319}";
}
function planetGlyph(name) {
  var _a;
  return (_a = PLANET_GLYPHS[name]) != null ? _a : "\u2605";
}
function formatPlanetLine(p) {
  const retro = p.isRetrograde ? " \u211E" : "";
  return `${planetGlyph(p.name)} ${p.sign} ${p.degreeInSign}\u02DA${retro}`;
}
function formatSkyAspectLine(a) {
  const g1 = planetGlyph(a.planet1);
  const g2 = planetGlyph(a.planet2);
  const r1 = a.planet1Retrograde ? " \u211E" : "";
  const r2 = a.planet2Retrograde ? " \u211E" : "";
  return `${g1}${r1} ${a.aspectSymbol} ${g2}${r2}`;
}

// src/techniques/ki.ts
var KI_TRIGRAMS_DATA = {
  1: { name: "Water", trigram: "\u2635", chinese: "Kan", element: "Water" },
  2: { name: "Earth", trigram: "\u2637", chinese: "Kun", element: "Earth" },
  3: { name: "Thunder", trigram: "\u2633", chinese: "Zhen", element: "Wood" },
  4: { name: "Wind", trigram: "\u2634", chinese: "Xun", element: "Wood" },
  5: { name: "Center", trigram: "\u262F", chinese: "Tai Chi", element: "Earth" },
  6: { name: "Heaven", trigram: "\u2630", chinese: "Qian", element: "Metal" },
  7: { name: "Lake", trigram: "\u2631", chinese: "Dui", element: "Metal" },
  8: { name: "Mountain", trigram: "\u2636", chinese: "Gen", element: "Earth" },
  9: { name: "Fire", trigram: "\u2632", chinese: "Li", element: "Fire" }
};
function kiTrigram(n) {
  return { number: n, ...KI_TRIGRAMS_DATA[n] };
}
var YEAR_TABLE = {
  1: [1909, 1918, 1927, 1936, 1945, 1954, 1963, 1972, 1981, 1990, 1999, 2008, 2017, 2026, 2035, 2044],
  2: [1908, 1917, 1926, 1935, 1944, 1953, 1962, 1971, 1980, 1989, 1998, 2007, 2016, 2025, 2034, 2043],
  3: [1907, 1916, 1925, 1934, 1943, 1952, 1961, 1970, 1979, 1988, 1997, 2006, 2015, 2024, 2033, 2042],
  4: [1906, 1915, 1924, 1933, 1942, 1951, 1960, 1969, 1978, 1987, 1996, 2005, 2014, 2023, 2032, 2041],
  5: [1905, 1914, 1923, 1932, 1941, 1950, 1959, 1968, 1977, 1986, 1995, 2004, 2013, 2022, 2031, 2040],
  6: [1904, 1913, 1922, 1931, 1940, 1949, 1958, 1967, 1976, 1985, 1994, 2003, 2012, 2021, 2030, 2039],
  7: [1903, 1912, 1921, 1930, 1939, 1948, 1957, 1966, 1975, 1984, 1993, 2002, 2011, 2020, 2029, 2038],
  8: [1902, 1911, 1920, 1929, 1938, 1947, 1956, 1965, 1974, 1983, 1992, 2001, 2010, 2019, 2028, 2037],
  9: [1901, 1910, 1919, 1928, 1937, 1946, 1955, 1964, 1973, 1982, 1991, 2e3, 2009, 2018, 2027, 2036]
};
var YEAR_TO_KI = {};
for (const [ki, years] of Object.entries(YEAR_TABLE)) {
  for (const y of years)
    YEAR_TO_KI[y] = Number(ki);
}
var MONTH_TABLE = [
  { start: [2, 4], end: [3, 5], values: [187, 225, 353, 481, 528, 656, 784, 822, 959] },
  { start: [3, 6], end: [4, 4], values: [178, 216, 344, 472, 519, 647, 775, 813, 941] },
  { start: [4, 5], end: [5, 4], values: [169, 297, 335, 463, 591, 638, 766, 894, 932] },
  { start: [5, 5], end: [6, 5], values: [151, 288, 326, 454, 582, 629, 757, 885, 923] },
  { start: [6, 6], end: [7, 6], values: [142, 279, 317, 445, 573, 611, 748, 876, 914] },
  { start: [7, 7], end: [8, 6], values: [133, 261, 398, 436, 564, 692, 739, 867, 995] },
  { start: [8, 7], end: [9, 7], values: [124, 252, 389, 427, 555, 683, 721, 858, 986] },
  { start: [9, 8], end: [10, 7], values: [115, 243, 371, 418, 546, 674, 712, 849, 977] },
  { start: [10, 8], end: [11, 6], values: [196, 234, 362, 499, 537, 665, 793, 831, 968] },
  { start: [11, 7], end: [12, 6], values: [187, 225, 353, 481, 528, 656, 784, 822, 959] },
  { start: [12, 7], end: [1, 4], values: [178, 216, 344, 472, 519, 647, 775, 813, 941] },
  { start: [1, 5], end: [2, 3], values: [169, 297, 335, 463, 591, 638, 766, 894, 932] }
];
var FLYING_SEQUENCE = [5, 6, 7, 8, 9, 1, 2, 3, 4];
var NUM_TO_IDX = {};
FLYING_SEQUENCE.forEach((n, i) => {
  NUM_TO_IDX[n] = i;
});
function dateInRange(month, day, start, end) {
  const dateVal = month * 100 + day;
  const startVal = start[0] * 100 + start[1];
  const endVal = end[0] * 100 + end[1];
  return startVal <= endVal ? dateVal >= startVal && dateVal <= endVal : dateVal >= startVal || dateVal <= endVal;
}
function calculateKiYear(year, month, day) {
  let effectiveYear = year;
  if (month < 2 || month === 2 && day < 4)
    effectiveYear = year - 1;
  if (YEAR_TO_KI[effectiveYear] !== void 0)
    return YEAR_TO_KI[effectiveYear];
  const offset = ((effectiveYear - 2026) % 9 + 9) % 9;
  const ki = 1 - offset;
  return ki <= 0 ? ki + 9 : ki;
}
function calculateKiAll(year, month, day) {
  const yearKi = calculateKiYear(year, month, day);
  for (const r of MONTH_TABLE) {
    if (dateInRange(month, day, r.start, r.end)) {
      const value = r.values[yearKi - 1];
      const s = String(value);
      const monthKi = Number(s[1]);
      const thirdKi = Number(s[2]);
      return [yearKi, monthKi, thirdKi];
    }
  }
  return [yearKi, 0, 0];
}
function calculateKi(d) {
  const y = d.getFullYear();
  const m = d.getMonth() + 1;
  const day = d.getDate();
  const [yearKi, monthKi, thirdKi] = calculateKiAll(y, m, day);
  return {
    date: isoDate(d),
    yearKi,
    monthKi,
    thirdKi,
    sequence: `${yearKi}.${monthKi}.${thirdKi}`,
    year: kiTrigram(yearKi),
    month: kiTrigram(monthKi),
    third: kiTrigram(thirdKi)
  };
}
function calculatePersonalCycle(natalYearKi, target) {
  const global = calculateKi(target);
  const shiftYear = -NUM_TO_IDX[global.yearKi];
  const personalYear = FLYING_SEQUENCE[((NUM_TO_IDX[natalYearKi] + shiftYear) % 9 + 9) % 9];
  const shiftMonth = -NUM_TO_IDX[global.monthKi];
  const personalMonth = FLYING_SEQUENCE[((NUM_TO_IDX[natalYearKi] + shiftMonth) % 9 + 9) % 9];
  return {
    date: isoDate(target),
    natalYearKi,
    globalYear: global.yearKi,
    globalMonth: global.monthKi,
    personalYear,
    personalMonth,
    personalYearInfo: kiTrigram(personalYear),
    personalMonthInfo: kiTrigram(personalMonth)
  };
}
function formatKiReport(ki) {
  const line = (n, kt, label) => `**${label}: ${n} ${kt.trigram} ${kt.name}** (${kt.chinese}) \u2014 ${kt.element}`;
  return [
    `# 9 Star Ki for ${ki.date}`,
    "",
    `**Ki Sequence:** ${ki.sequence}`,
    "",
    line(ki.yearKi, ki.year, "Year Ki"),
    line(ki.monthKi, ki.month, "Month Ki"),
    line(ki.thirdKi, ki.third, "Third Ki")
  ].join("\n");
}
function isoDate(d) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

// src/techniques/hexagram.ts
var HEXAGRAMS = {
  1: { name: "The Creative", chinese: "Qian", upper: "Heaven", lower: "Heaven", judgment: "Sublime success through perseverance." },
  2: { name: "The Receptive", chinese: "Kun", upper: "Earth", lower: "Earth", judgment: "Sublime success; receptive devotion brings reward." },
  3: { name: "Difficulty at the Beginning", chinese: "Zhun", upper: "Water", lower: "Thunder", judgment: "It furthers one to appoint helpers; do not act alone." },
  4: { name: "Youthful Folly", chinese: "Meng", upper: "Mountain", lower: "Water", judgment: "The youth must seek the master; the master does not chase." },
  5: { name: "Waiting", chinese: "Xu", upper: "Water", lower: "Heaven", judgment: "Wait sincerely; crossing the great water furthers." },
  6: { name: "Conflict", chinese: "Song", upper: "Heaven", lower: "Water", judgment: "Halfway brings good fortune; carrying it through, misfortune." },
  7: { name: "The Army", chinese: "Shi", upper: "Earth", lower: "Water", judgment: "The army needs a strong leader; perseverance brings reward." },
  8: { name: "Holding Together", chinese: "Bi", upper: "Water", lower: "Earth", judgment: "Union sought now brings good fortune; latecomers, misfortune." },
  9: { name: "Small Taming Power", chinese: "Xiao Chu", upper: "Wind", lower: "Heaven", judgment: "Dense clouds, no rain; the small holds back the great." },
  10: { name: "Treading", chinese: "Lu", upper: "Heaven", lower: "Lake", judgment: "Treading on the tiger's tail; it does not bite." },
  11: { name: "Peace", chinese: "Tai", upper: "Earth", lower: "Heaven", judgment: "The small departs, the great approaches." },
  12: { name: "Standstill", chinese: "Pi", upper: "Heaven", lower: "Earth", judgment: "Evil people do not further the perseverance of the superior." },
  13: { name: "Fellowship with Others", chinese: "Tong Ren", upper: "Heaven", lower: "Fire", judgment: "Fellowship in the open; crossing the great water furthers." },
  14: { name: "Great Possession", chinese: "Da You", upper: "Fire", lower: "Heaven", judgment: "Supreme success; modesty preserves the great." },
  15: { name: "Modesty", chinese: "Qian", upper: "Earth", lower: "Mountain", judgment: "The superior person carries things through; success." },
  16: { name: "Enthusiasm", chinese: "Yu", upper: "Thunder", lower: "Earth", judgment: "It furthers to install helpers and to set armies marching." },
  17: { name: "Following", chinese: "Sui", upper: "Lake", lower: "Thunder", judgment: "Supreme success; perseverance brings reward." },
  18: { name: "Work on the Decayed", chinese: "Gu", upper: "Mountain", lower: "Wind", judgment: "Crossing the great water furthers; three days before, three days after." },
  19: { name: "Approach", chinese: "Lin", upper: "Earth", lower: "Lake", judgment: "Supreme success; in the eighth month, misfortune." },
  20: { name: "Contemplation", chinese: "Guan", upper: "Wind", lower: "Earth", judgment: "The ablution has been made; the offering not yet brought." },
  21: { name: "Biting Through", chinese: "Shi He", upper: "Fire", lower: "Thunder", judgment: "Success; it is favorable to let justice be administered." },
  22: { name: "Grace", chinese: "Bi", upper: "Mountain", lower: "Fire", judgment: "Small success in small matters." },
  23: { name: "Splitting Apart", chinese: "Bo", upper: "Mountain", lower: "Earth", judgment: "It does not further to go anywhere." },
  24: { name: "Return", chinese: "Fu", upper: "Earth", lower: "Thunder", judgment: "Friends come without blame; the way returns on the seventh day." },
  25: { name: "Innocence", chinese: "Wu Wang", upper: "Heaven", lower: "Thunder", judgment: "If the act is not right, misfortune; nowhere furthers." },
  26: { name: "Great Taming Power", chinese: "Da Chu", upper: "Mountain", lower: "Heaven", judgment: "Perseverance furthers; crossing the great water furthers." },
  27: { name: "Nourishment", chinese: "Yi", upper: "Mountain", lower: "Thunder", judgment: "Pay heed to what gives nourishment, and what one seeks to fill the mouth." },
  28: { name: "Preponderance of the Great", chinese: "Da Guo", upper: "Lake", lower: "Wind", judgment: "The ridgepole sags; success in undertakings." },
  29: { name: "The Abysmal", chinese: "Kan", upper: "Water", lower: "Water", judgment: "If sincere, success in the heart; actions bring esteem." },
  30: { name: "The Clinging", chinese: "Li", upper: "Fire", lower: "Fire", judgment: "Perseverance furthers; caring for the cow brings good fortune." },
  31: { name: "Influence", chinese: "Xian", upper: "Lake", lower: "Mountain", judgment: "Success; perseverance furthers. Taking a maiden brings good fortune." },
  32: { name: "Duration", chinese: "Heng", upper: "Thunder", lower: "Wind", judgment: "Success without blame; perseverance furthers a goal." },
  33: { name: "Retreat", chinese: "Dun", upper: "Heaven", lower: "Mountain", judgment: "Success in small matters; perseverance furthers." },
  34: { name: "The Power of the Great", chinese: "Da Zhuang", upper: "Thunder", lower: "Heaven", judgment: "Perseverance furthers." },
  35: { name: "Progress", chinese: "Jin", upper: "Fire", lower: "Earth", judgment: "The powerful prince receives horses in abundance." },
  36: { name: "Darkening of the Light", chinese: "Ming Yi", upper: "Earth", lower: "Fire", judgment: "In adversity, perseverance furthers." },
  37: { name: "The Family", chinese: "Jia Ren", upper: "Wind", lower: "Fire", judgment: "The perseverance of the woman furthers." },
  38: { name: "Opposition", chinese: "Kui", upper: "Fire", lower: "Lake", judgment: "In small matters, good fortune." },
  39: { name: "Obstruction", chinese: "Jian", upper: "Water", lower: "Mountain", judgment: "The southwest furthers; seeing the great person furthers." },
  40: { name: "Deliverance", chinese: "Xie", upper: "Thunder", lower: "Water", judgment: "The southwest furthers; if there is no place to go, return brings fortune." },
  41: { name: "Decrease", chinese: "Sun", upper: "Mountain", lower: "Lake", judgment: "If sincere, supreme good fortune without blame." },
  42: { name: "Increase", chinese: "Yi", upper: "Wind", lower: "Thunder", judgment: "It furthers to undertake something; crossing the great water furthers." },
  43: { name: "Breakthrough", chinese: "Guai", upper: "Lake", lower: "Heaven", judgment: "A resolute announcement at court; there is danger." },
  44: { name: "Coming to Meet", chinese: "Gou", upper: "Heaven", lower: "Wind", judgment: "The maiden is powerful; do not marry such a maiden." },
  45: { name: "Gathering Together", chinese: "Cui", upper: "Lake", lower: "Earth", judgment: "The king approaches his temple; seeing the great person furthers." },
  46: { name: "Pushing Upward", chinese: "Sheng", upper: "Earth", lower: "Wind", judgment: "Supreme success; departure toward the south brings fortune." },
  47: { name: "Oppression", chinese: "Kun", upper: "Lake", lower: "Water", judgment: "Success; for the great person, good fortune without blame." },
  48: { name: "The Well", chinese: "Jing", upper: "Water", lower: "Wind", judgment: "The town may change; the well does not change." },
  49: { name: "Revolution", chinese: "Ge", upper: "Lake", lower: "Fire", judgment: "On your own day, you are believed; supreme success; perseverance furthers." },
  50: { name: "The Caldron", chinese: "Ding", upper: "Fire", lower: "Wind", judgment: "Supreme good fortune; success." },
  51: { name: "The Arousing", chinese: "Zhen", upper: "Thunder", lower: "Thunder", judgment: "Shock terrifies for a hundred miles; the offerer does not drop the sacrificial spoon." },
  52: { name: "Keeping Still", chinese: "Gen", upper: "Mountain", lower: "Mountain", judgment: "Keeping the back still; not perceiving the body." },
  53: { name: "Development", chinese: "Jian", upper: "Wind", lower: "Mountain", judgment: "The maiden is given in marriage; good fortune; perseverance furthers." },
  54: { name: "The Marrying Maiden", chinese: "Gui Mei", upper: "Thunder", lower: "Lake", judgment: "Undertakings bring misfortune; nothing that would further." },
  55: { name: "Abundance", chinese: "Feng", upper: "Thunder", lower: "Fire", judgment: "The king attains abundance; be not sad. Be like the sun at midday." },
  56: { name: "The Wanderer", chinese: "Lu", upper: "Fire", lower: "Mountain", judgment: "Success in small things; perseverance brings fortune to the wanderer." },
  57: { name: "The Gentle", chinese: "Xun", upper: "Wind", lower: "Wind", judgment: "Success through what is small; seeing the great person furthers." },
  58: { name: "The Joyous", chinese: "Dui", upper: "Lake", lower: "Lake", judgment: "Success; perseverance is favorable." },
  59: { name: "Dispersion", chinese: "Huan", upper: "Wind", lower: "Water", judgment: "The king approaches his temple; crossing the great water furthers." },
  60: { name: "Limitation", chinese: "Jie", upper: "Water", lower: "Lake", judgment: "Galling limitation must not be persevered in." },
  61: { name: "Inner Truth", chinese: "Zhong Fu", upper: "Wind", lower: "Lake", judgment: "Pigs and fishes; crossing the great water furthers." },
  62: { name: "Preponderance of the Small", chinese: "Xiao Guo", upper: "Thunder", lower: "Mountain", judgment: "Small things may be done; great things should not be done." },
  63: { name: "After Completion", chinese: "Ji Ji", upper: "Water", lower: "Fire", judgment: "Success in small matters; perseverance furthers; in the beginning, fortune; at the end, disorder." },
  64: { name: "Before Completion", chinese: "Wei Ji", upper: "Fire", lower: "Water", judgment: "Success; the little fox is almost across when his tail gets wet." }
};
var TRIGRAM_BITS = {
  Heaven: "111",
  Earth: "000",
  Lake: "110",
  Mountain: "001",
  Fire: "101",
  Water: "010",
  Thunder: "100",
  Wind: "011"
};
var KING_WEN = {};
for (const [numStr, h] of Object.entries(HEXAGRAMS)) {
  const lower = TRIGRAM_BITS[h.lower];
  const upper = TRIGRAM_BITS[h.upper];
  if (!lower || !upper)
    throw new Error(`Unknown trigram for hex ${numStr}`);
  KING_WEN[lower + upper] = Number(numStr);
}
function getHexagram(num) {
  const h = HEXAGRAMS[num];
  if (!h)
    throw new Error(`Unknown hexagram ${num}`);
  return { number: num, ...h };
}
function castLine(rng = Math.random) {
  const coin = () => rng() < 0.5 ? 2 : 3;
  const sum = coin() + coin() + coin();
  return {
    value: sum,
    yin: sum === 6 || sum === 8,
    changing: sum === 6 || sum === 9
  };
}
function hexagramNumberFromLines(lines, useChangedLines = false) {
  const bits = lines.map((l) => {
    const yin = useChangedLines && l.changing ? !l.yin : l.yin;
    return yin ? "0" : "1";
  }).join("");
  return hexagramNumberFromBits(bits);
}
function hexagramNumberFromBits(bits) {
  const num = KING_WEN[bits];
  if (!num)
    throw new Error(`No hexagram for binary ${bits}`);
  return num;
}
function castHexagram(rng = Math.random) {
  const lines = Array.from({ length: 6 }, () => castLine(rng));
  const primaryNum = hexagramNumberFromLines(lines, false);
  const changingLines = lines.map((l, i) => l.changing ? i + 1 : 0).filter((n) => n > 0);
  const relating = changingLines.length > 0 ? getHexagram(hexagramNumberFromLines(lines, true)) : null;
  return { lines, primary: getHexagram(primaryNum), relating, changingLines };
}
var LINE_GLYPHS = {
  yangStable: "\u2501\u2501\u2501\u2501\u2501\u2501\u2501",
  yinStable: "\u2501\u2501   \u2501\u2501",
  yangChange: "\u2501\u2501\u2501\u25CB\u2501\u2501\u2501",
  yinChange: "\u2501\u2501 x \u2501\u2501"
};
function renderHexagram(lines) {
  return [...lines].reverse().map((l) => {
    if (l.value === 9)
      return LINE_GLYPHS.yangChange;
    if (l.value === 6)
      return LINE_GLYPHS.yinChange;
    if (l.value === 7)
      return LINE_GLYPHS.yangStable;
    return LINE_GLYPHS.yinStable;
  }).join("\n");
}
function formatCast(cast) {
  const lines = [
    `# Hexagram ${cast.primary.number}: ${cast.primary.name} (${cast.primary.chinese})`,
    `*${cast.primary.upper} above, ${cast.primary.lower} below*`,
    "",
    "```",
    renderHexagram(cast.lines),
    "```",
    "",
    `**Judgment:** ${cast.primary.judgment}`
  ];
  if (cast.relating) {
    lines.push(
      "",
      `## Changing into ${cast.relating.number}: ${cast.relating.name} (${cast.relating.chinese})`,
      `Changing lines: ${cast.changingLines.join(", ")}`,
      `**Relating judgment:** ${cast.relating.judgment}`
    );
  }
  return lines.join("\n");
}

// main.ts
var MoonPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.api = {
      getMoonData: this.getMoonData.bind(this),
      getMoonPhaseEmoji: moonPhaseEmoji,
      getPlanetGlyph: planetGlyph,
      getCurrentMoonPhase: this.getCurrentMoonPhase.bind(this),
      getCurrentMoonDegree: this.getCurrentMoonDegree.bind(this),
      getWeeklyPhase: this.getWeeklyPhase.bind(this),
      getWeeklyMajorPhase: this.getWeeklyMajorPhase.bind(this),
      getPlanetaryData: this.getPlanetaryData.bind(this),
      getAspectsData: this.getAspectsData.bind(this),
      getNatalTransits: this.getNatalTransits.bind(this),
      getNatalChart: this.getNatalChart.bind(this),
      listSavedCharts: this.listSavedCharts.bind(this),
      // Techniques
      getTodaysKi: this.getTodaysKi.bind(this),
      getNatalKi: this.getNatalKi.bind(this),
      getDailyHexagram: this.getDailyHexagram.bind(this),
      getMidpointTransits: this.getMidpointTransits.bind(this),
      getNextEclipse: this.getNextEclipse.bind(this),
      getDashas: this.getDashas.bind(this)
    };
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new MoonSettingTab(this.app, this));
    window.ObsidianMoon = this.api;
    window.MoonPhasePlugin = this.api;
    this.addCommand({
      id: "current-moon-phase",
      name: "Current Moon Phase",
      editorCallback: (editor) => {
        this.getCurrentMoonPhase().then((s) => editor.replaceSelection(s));
      }
    });
    this.addCommand({
      id: "current-moon-degree",
      name: "Current Moon Degree",
      editorCallback: (editor) => {
        this.getCurrentMoonDegree().then((s) => editor.replaceSelection(s));
      }
    });
    this.addCommand({
      id: "weekly-phase",
      name: "Weekly Phase",
      editorCallback: (editor) => {
        this.getWeeklyPhase().then((s) => editor.replaceSelection(s));
      }
    });
    this.addCommand({
      id: "planetary-positions",
      name: "All Planetary Positions",
      editorCallback: (editor) => {
        this.getPlanetaryData().then((data) => {
          editor.replaceSelection(data.planets.map(formatPlanetLine).join("\n"));
        }).catch((err) => this.handleError(editor, "planetary data", err));
      }
    });
    for (const planetName of PLANETS) {
      this.addCommand({
        id: `${planetName.toLowerCase()}-position`,
        name: `${planetName} Position`,
        editorCallback: (editor) => {
          this.getPlanetaryData().then((data) => {
            const planet = data.planets.find((p) => p.name === planetName);
            editor.replaceSelection(planet ? formatPlanetLine(planet) : `Error: ${planetName} data not found`);
          }).catch((err) => this.handleError(editor, `${planetName} data`, err));
        }
      });
    }
    this.addCommand({
      id: "all-aspects",
      name: "All Current Aspects",
      editorCallback: (editor) => {
        this.getEffectiveAspects().then((aspects) => {
          if (aspects.length === 0) {
            editor.replaceSelection("No significant aspects currently.");
            return;
          }
          editor.replaceSelection(aspects.map(formatSkyAspectLine).join("\n"));
        }).catch((err) => this.handleError(editor, "aspects data", err));
      }
    });
    for (const planetName of PLANETS) {
      this.addCommand({
        id: `${planetName.toLowerCase()}-aspects`,
        name: `${planetName} Aspects`,
        editorCallback: (editor) => {
          this.getEffectiveAspects().then((aspects) => {
            const relevant = aspects.filter((a) => a.planet1 === planetName || a.planet2 === planetName);
            if (relevant.length === 0) {
              editor.replaceSelection(`No significant aspects for ${planetName} currently.`);
              return;
            }
            const out = relevant.map((a) => {
              if (a.planet1 === planetName)
                return formatSkyAspectLine(a);
              return formatSkyAspectLine({
                ...a,
                planet1: a.planet2,
                planet2: a.planet1,
                planet1Sign: a.planet2Sign,
                planet2Sign: a.planet1Sign,
                planet1Retrograde: a.planet2Retrograde,
                planet2Retrograde: a.planet1Retrograde
              });
            }).join("\n");
            editor.replaceSelection(out);
          }).catch((err) => this.handleError(editor, `${planetName} aspects`, err));
        }
      });
    }
    for (const aspectName of ["Conjunction", "Opposition", "Trine", "Square", "Sextile"]) {
      this.addCommand({
        id: `${aspectName.toLowerCase()}-aspects`,
        name: `${aspectName} Aspects`,
        editorCallback: (editor) => {
          this.getEffectiveAspects().then((aspects) => {
            const relevant = aspects.filter((a) => a.aspectName === aspectName);
            if (relevant.length === 0) {
              editor.replaceSelection(`No ${aspectName} aspects currently.`);
              return;
            }
            editor.replaceSelection(relevant.map(formatSkyAspectLine).join("\n"));
          }).catch((err) => this.handleError(editor, `${aspectName} aspects`, err));
        }
      });
    }
    this.addCommand({
      id: "cast-hexagram",
      name: "Cast Hexagram",
      editorCallback: (editor) => {
        if (!this.settings.techniques.hexagram) {
          new import_obsidian.Notice('Enable "Hexagram" in the Techniques settings tab first.');
          return;
        }
        editor.replaceSelection(this.getDailyHexagram());
      }
    });
    this.addCommand({
      id: "todays-ki",
      name: "Today's 9 Star Ki",
      editorCallback: (editor) => {
        if (!this.settings.techniques.ki) {
          new import_obsidian.Notice('Enable "Ki" in the Techniques settings tab first.');
          return;
        }
        editor.replaceSelection(this.getTodaysKi());
      }
    });
    this.addCommand({
      id: "natal-ki",
      name: "Natal 9 Star Ki (selected chart / birth date)",
      editorCallback: (editor) => {
        if (!this.settings.techniques.ki) {
          new import_obsidian.Notice('Enable "Ki" in the Techniques settings tab first.');
          return;
        }
        this.getNatalKi().then((text) => editor.replaceSelection(text)).catch((err) => this.handleError(editor, "natal Ki", err));
      }
    });
    this.addCommand({
      id: "midpoint-transits",
      name: "Midpoint Transits (selected chart)",
      editorCallback: (editor) => {
        if (!this.settings.techniques.midpoints) {
          new import_obsidian.Notice('Enable "Midpoints" in the Techniques settings tab first.');
          return;
        }
        this.getMidpointTransits().then((text) => editor.replaceSelection(text)).catch((err) => this.handleError(editor, "midpoint transits", err));
      }
    });
    this.addCommand({
      id: "next-eclipse",
      name: "Next Eclipse",
      editorCallback: (editor) => {
        if (!this.settings.techniques.eclipses) {
          new import_obsidian.Notice('Enable "Eclipses" in the Techniques settings tab first.');
          return;
        }
        this.getNextEclipse().then((text) => editor.replaceSelection(text)).catch((err) => this.handleError(editor, "next eclipse", err));
      }
    });
    this.addCommand({
      id: "dashas",
      name: "Vimshottari Dashas (selected chart)",
      editorCallback: (editor) => {
        if (!this.settings.techniques.dashas) {
          new import_obsidian.Notice('Enable "Dashas" in the Techniques settings tab first.');
          return;
        }
        this.getDashas().then((text) => editor.replaceSelection(text)).catch((err) => this.handleError(editor, "dashas", err));
      }
    });
  }
  onunload() {
    try {
      delete window.ObsidianMoon;
      delete window.MoonPhasePlugin;
    } catch (e) {
    }
  }
  /* ── Settings IO ── */
  async loadSettings() {
    this.settings = migrateSettings(await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /* ── HTTP via requestUrl (no CORS preflight from app:// origin) ── */
  async req(path, opts) {
    var _a, _b;
    const url = joinUrl(this.settings.serverUrl, path);
    const res = await (0, import_obsidian.requestUrl)({
      url,
      method: (_a = opts == null ? void 0 : opts.method) != null ? _a : "GET",
      contentType: (opts == null ? void 0 : opts.body) ? "application/json" : void 0,
      body: (opts == null ? void 0 : opts.body) ? JSON.stringify(opts.body) : void 0,
      throw: false
    });
    if (res.status < 200 || res.status >= 300) {
      throw new Error(`HTTP ${res.status} from ${url}: ${((_b = res.text) != null ? _b : "").slice(0, 200)}`);
    }
    return res.json;
  }
  /* ── Data fetchers (real baratie endpoints) ── */
  async getMoonData() {
    return this.req("/moon-now");
  }
  async getPlanetaryData() {
    const data = await this.req("/planets-now");
    return {
      ...data,
      planets: data.planets.filter((p) => this.settings.planets[p.name])
    };
  }
  async getAspectsData() {
    const data = await this.req("/aspects-now");
    return { ...data, aspects: filterSkyAspects(data.aspects, this.settings) };
  }
  async getNatalTransits(chartName) {
    const name = (chartName != null ? chartName : this.settings.selectedChart).trim();
    if (!name)
      throw new Error("No saved chart selected \u2014 pick one in Obsidian Moon settings.");
    const qs = natalTransitQuery(this.settings);
    return this.req(`/transits/${encodeURIComponent(name)}/now${qs}`);
  }
  async getNatalChart(chartName) {
    const name = (chartName != null ? chartName : this.settings.selectedChart).trim();
    if (!name)
      throw new Error("No saved chart selected.");
    return this.req(`/chart/${encodeURIComponent(name)}`);
  }
  async listSavedCharts() {
    const data = await this.req("/charts");
    return Array.isArray(data == null ? void 0 : data.charts) ? data.charts : [];
  }
  async generateChart(body) {
    return this.req("/generate-chart", { method: "POST", body });
  }
  /* Routes through whichever mode is active. */
  async getEffectiveAspects() {
    if (this.settings.useNatalChart && this.settings.selectedChart) {
      const data = await this.getNatalTransits();
      return filterNatalTransits(data.transits, this.settings);
    }
    return (await this.getAspectsData()).aspects;
  }
  /* ── Techniques ── */
  /** Pure-TS: today's 9 Star Ki sequence. */
  getTodaysKi() {
    return formatKiReport(calculateKi(new Date()));
  }
  /** Pure-TS: natal Ki + personal cycle for the day. Uses settings.birthDate
   * (falls back to fetching the selected chart's birth date from Helios). */
  async getNatalKi() {
    const birthIso = this.settings.birthDate || await this.fetchChartBirthDate();
    if (!birthIso) {
      throw new Error("Set Birth Date in settings, or pick a saved chart that has one.");
    }
    const [y, m, d] = birthIso.split("-").map(Number);
    const birth = new Date(y, m - 1, d);
    const natal = calculateKi(birth);
    const cycle = calculatePersonalCycle(natal.yearKi, new Date());
    return [
      `# Natal 9 Star Ki \u2014 born ${birthIso}`,
      "",
      `**Natal sequence:** ${natal.sequence}`,
      `**Today's personal cycle:** year ${cycle.personalYear} ${cycle.personalYearInfo.trigram} ${cycle.personalYearInfo.name}, month ${cycle.personalMonth} ${cycle.personalMonthInfo.trigram} ${cycle.personalMonthInfo.name}`,
      "",
      formatKiReport(natal)
    ].join("\n");
  }
  /** Pure-TS: cast a hexagram. */
  getDailyHexagram() {
    return formatCast(castHexagram());
  }
  /** Helios: midpoint transits to a saved chart. */
  async getMidpointTransits(chartName) {
    var _a;
    const name = (chartName != null ? chartName : this.settings.selectedChart).trim();
    if (!name)
      throw new Error("Pick a saved chart in Natal Chart settings first.");
    const data = await this.req(
      `/midpoint-transits/${encodeURIComponent(name)}?orb=${this.settings.midpointOrb}`
    );
    const rows = (_a = data == null ? void 0 : data.midpointTransits) != null ? _a : [];
    if (rows.length === 0)
      return `No midpoint transits within ${this.settings.midpointOrb}\xB0 for ${name}.`;
    return [`# Midpoint transits to ${name}`, "", ...rows.map((r) => `- ${r.transit} ${r.aspect} ${r.midpoint} (orb ${r.orb}\xB0)`)].join("\n");
  }
  /** Helios: next eclipse within the configured lookahead window. */
  async getNextEclipse() {
    var _a;
    const start = new Date();
    const end = new Date();
    end.setMonth(end.getMonth() + this.settings.eclipseLookaheadMonths);
    const startIso = start.toISOString().slice(0, 10);
    const endIso = end.toISOString().slice(0, 10);
    const data = await this.req(
      `/eclipses?start=${startIso}&end=${endIso}`
    );
    const first = (_a = data == null ? void 0 : data.eclipses) == null ? void 0 : _a[0];
    if (!first)
      return `No eclipses in the next ${this.settings.eclipseLookaheadMonths} months.`;
    const where = first.sign && first.degree ? ` at ${first.degree}\u02DA ${first.sign}` : "";
    return `Next eclipse: ${first.type} on ${first.date}${where}.`;
  }
  /** Helios: Vimshottari dasha periods for a saved chart. */
  async getDashas(chartName, levels = 2) {
    var _a;
    const name = (chartName != null ? chartName : this.settings.selectedChart).trim();
    if (!name)
      throw new Error("Pick a saved chart in Natal Chart settings first.");
    const data = await this.req(
      `/dashas/${encodeURIComponent(name)}?levels=${levels}`
    );
    const rows = (_a = data == null ? void 0 : data.dashas) != null ? _a : [];
    if (rows.length === 0)
      return `No dasha data for ${name}.`;
    return [`# Vimshottari dashas for ${name}`, "", ...rows.map((r) => `- **${r.planet}** ${r.start} \u2192 ${r.end}`)].join("\n");
  }
  async fetchChartBirthDate() {
    var _a, _b;
    if (!this.settings.selectedChart)
      return "";
    try {
      const chart = await this.getNatalChart();
      return (_b = (_a = chart == null ? void 0 : chart.birthData) == null ? void 0 : _a.date) != null ? _b : "";
    } catch (e) {
      return "";
    }
  }
  async getWeeklyMajorPhase() {
    var _a, _b;
    try {
      const data = await this.req(
        "/weekly-major-phase"
      );
      if (data == null ? void 0 : data.moonPhase) {
        return { date: (_a = data.date) != null ? _a : "", moonPhase: data.moonPhase, moonSign: (_b = data.moonSign) != null ? _b : "" };
      }
      return null;
    } catch (err) {
      console.error("Error fetching weekly moon phase:", err);
      return null;
    }
  }
  /* ── Templater-friendly string helpers ── */
  async getCurrentMoonPhase() {
    try {
      const m = await this.getMoonData();
      return `${moonPhaseEmoji(m.moonPhase)} ${m.moonSign}`;
    } catch (e) {
      return "Error fetching moon data";
    }
  }
  async getCurrentMoonDegree() {
    try {
      const m = await this.getMoonData();
      return `${moonPhaseEmoji(m.moonPhase)} ${m.moonSign} ${m.degreeInSign}\u02DA`;
    } catch (e) {
      return "Error fetching moon data";
    }
  }
  async getWeeklyPhase() {
    const phase = await this.getWeeklyMajorPhase();
    if (!phase)
      return "No major moon phase this week.";
    return `${moonPhaseEmoji(phase.moonPhase)} ${phase.moonSign}`;
  }
  handleError(editor, what, err) {
    console.error(`Error fetching ${what}:`, err);
    editor.replaceSelection(`Error fetching ${what}. Check console for details.`);
  }
};
var MoonSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.activeTab = "general";
    this.locationSearchTimer = null;
    this.cachedCharts = null;
    this.chartDraft = {
      name: "",
      date: "",
      time: "12:00",
      locationName: "",
      latitude: NaN,
      longitude: NaN,
      timezone: typeof Intl !== "undefined" ? Intl.DateTimeFormat().resolvedOptions().timeZone : "UTC"
    };
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Obsidian Moon" });
    const tabs = [
      { id: "general", label: "General" },
      { id: "chart", label: "Natal Chart" },
      { id: "planets", label: "Planets" },
      { id: "aspects", label: "Aspects" },
      { id: "techniques", label: "Techniques" }
    ];
    const bar = containerEl.createDiv({ cls: "moon-tab-bar" });
    for (const t of tabs) {
      const btn = bar.createEl("button", {
        text: t.label,
        cls: "moon-tab" + (this.activeTab === t.id ? " moon-tab-active" : "")
      });
      btn.addEventListener("click", () => {
        this.activeTab = t.id;
        this.display();
      });
    }
    const body = containerEl.createDiv({ cls: "moon-tab-content" });
    switch (this.activeTab) {
      case "general":
        this.renderGeneral(body);
        break;
      case "chart":
        this.renderChart(body);
        break;
      case "planets":
        this.renderPlanets(body);
        break;
      case "aspects":
        this.renderAspects(body);
        break;
      case "techniques":
        this.renderTechniques(body);
        break;
    }
  }
  /* ── General ── */
  renderGeneral(c) {
    new import_obsidian.Setting(c).setName("Server URL").setDesc("URL to your Sweph Astrological API server (e.g. http://baratie:3000).").addText((text) => text.setPlaceholder("http://localhost:3000").setValue(this.plugin.settings.serverUrl).onChange(async (value) => {
      this.plugin.settings.serverUrl = normalizeBaseUrl(value);
      await this.plugin.saveSettings();
    }));
    const testWrap = c.createDiv({ cls: "moon-test-wrap" });
    new import_obsidian.Setting(testWrap).setName("Test server connection").setDesc("Pings /test on the configured server.").addButton((btn) => btn.setButtonText("Test").setCta().onClick(async () => {
      var _a, _b, _c;
      btn.setDisabled(true).setButtonText("Testing\u2026");
      try {
        const res = await (0, import_obsidian.requestUrl)({
          url: joinUrl(this.plugin.settings.serverUrl, "/test"),
          throw: false
        });
        if (res.status >= 200 && res.status < 300) {
          new import_obsidian.Notice(`Server OK: ${(_b = (_a = res.json) == null ? void 0 : _a.status) != null ? _b : "reachable"}`);
        } else {
          new import_obsidian.Notice(`Server returned ${res.status}`);
        }
      } catch (err) {
        new import_obsidian.Notice(`Connection failed: ${(_c = err == null ? void 0 : err.message) != null ? _c : err}`);
      } finally {
        btn.setDisabled(false).setButtonText("Test");
      }
    }));
  }
  /* ── Natal Chart ── */
  renderChart(c) {
    c.createEl("p", {
      cls: "moon-tab-intro",
      text: 'Pick one of the natal charts saved on your Sweph server. When "Use natal chart for transits" is on, the aspect commands return transits to that chart instead of plain sky-to-sky aspects.'
    });
    const pickerSetting = new import_obsidian.Setting(c).setName("Saved chart").setDesc("Charts saved on the server via /generate-chart.");
    const dropdown = pickerSetting.controlEl.createEl("select", { cls: "dropdown" });
    const refreshBtn = pickerSetting.controlEl.createEl("button", { text: "Refresh" });
    refreshBtn.addEventListener("click", async () => {
      this.cachedCharts = null;
      await this.populateChartDropdown(dropdown);
    });
    this.populateChartDropdown(dropdown);
    dropdown.addEventListener("change", async () => {
      this.plugin.settings.selectedChart = dropdown.value;
      await this.plugin.saveSettings();
    });
    new import_obsidian.Setting(c).setName("Use natal chart for transits").setDesc("When on, the aspect commands return transits aspecting the saved chart's planets (via /transits/:name/now).").addToggle((t) => t.setValue(this.plugin.settings.useNatalChart).onChange(async (v) => {
      this.plugin.settings.useNatalChart = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(c).setName("Major aspects only").setDesc("Sends ?major=true to /transits/:name/now. Conjunction / Opposition / Trine / Square / Sextile only.").addToggle((t) => t.setValue(this.plugin.settings.majorOnly).onChange(async (v) => {
      this.plugin.settings.majorOnly = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(c).setName("Natal orb (degrees)").setDesc("Tightness of natal transit aspects. The server applies this to /transits/:name/now.").addSlider((s) => s.setLimits(1, 12, 0.5).setValue(this.plugin.settings.natalOrb).setDynamicTooltip().onChange(async (v) => {
      this.plugin.settings.natalOrb = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(c).addButton((btn) => btn.setButtonText("Preview transits").setCta().onClick(async () => {
      var _a;
      if (!this.plugin.settings.selectedChart) {
        new import_obsidian.Notice("Pick a saved chart first.");
        return;
      }
      btn.setDisabled(true).setButtonText("Loading\u2026");
      try {
        const data = await this.plugin.getNatalTransits();
        const lines = filterNatalTransits(data.transits, this.plugin.settings).slice(0, 10).map(formatSkyAspectLine);
        new import_obsidian.Notice(`Top transits for ${data.name}:
${lines.join("\n")}`, 12e3);
      } catch (err) {
        new import_obsidian.Notice(`Preview failed: ${(_a = err == null ? void 0 : err.message) != null ? _a : err}`, 8e3);
      } finally {
        btn.setDisabled(false).setButtonText("Preview transits");
      }
    }));
    c.createEl("h3", { text: "Create a new chart" });
    c.createEl("p", {
      cls: "moon-tab-intro",
      text: "Fill in birth details and save the chart to your Sweph server. Once saved, it appears in the dropdown above."
    });
    new import_obsidian.Setting(c).setName("Chart name").setDesc("A short identifier, e.g. your first name. Used as the URL slug.").addText((t) => t.setPlaceholder("chris").setValue(this.chartDraft.name).onChange((v) => {
      this.chartDraft.name = v.trim();
    }));
    const dateSetting = new import_obsidian.Setting(c).setName("Birth date");
    const dateInput = dateSetting.controlEl.createEl("input", { type: "date" });
    dateInput.value = this.chartDraft.date;
    dateInput.addEventListener("change", () => {
      this.chartDraft.date = dateInput.value;
    });
    const timeSetting = new import_obsidian.Setting(c).setName("Birth time").setDesc("Local time at the birth location (24h). Accuracy matters most for the Ascendant / houses.");
    const timeInput = timeSetting.controlEl.createEl("input", { type: "time" });
    timeInput.value = this.chartDraft.time;
    timeInput.step = "60";
    timeInput.addEventListener("change", () => {
      this.chartDraft.time = timeInput.value;
    });
    const locWrap = c.createDiv({ cls: "moon-loc-wrap" });
    new import_obsidian.Setting(locWrap).setName("Location").setDesc("Type a city, then pick a result to auto-fill latitude / longitude.").addText((text) => {
      text.setPlaceholder("e.g. Orlando, FL").setValue(this.chartDraft.locationName).onChange((value) => {
        if (this.locationSearchTimer)
          window.clearTimeout(this.locationSearchTimer);
        const query = value.trim();
        if (query.length < 3) {
          results.empty();
          return;
        }
        this.locationSearchTimer = window.setTimeout(
          () => this.searchLocations(query, results),
          400
        );
      });
      return text;
    });
    const results = locWrap.createDiv({ cls: "moon-loc-results" });
    new import_obsidian.Setting(c).setName("Latitude").setDesc("Decimal degrees, north positive.").addText((t) => t.setPlaceholder("28.5383").setValue(Number.isFinite(this.chartDraft.latitude) ? String(this.chartDraft.latitude) : "").onChange((v) => {
      this.chartDraft.latitude = parseFloat(v);
    }));
    new import_obsidian.Setting(c).setName("Longitude").setDesc("Decimal degrees, east positive.").addText((t) => t.setPlaceholder("-81.3792").setValue(Number.isFinite(this.chartDraft.longitude) ? String(this.chartDraft.longitude) : "").onChange((v) => {
      this.chartDraft.longitude = parseFloat(v);
    }));
    new import_obsidian.Setting(c).setName("Birth timezone").setDesc("IANA timezone of the birth location (e.g. America/New_York).").addText((t) => t.setPlaceholder("America/New_York").setValue(this.chartDraft.timezone).onChange((v) => {
      this.chartDraft.timezone = v.trim();
    }));
    new import_obsidian.Setting(c).addButton((btn) => btn.setButtonText("Save chart").setCta().onClick(async () => {
      var _a;
      btn.setDisabled(true).setButtonText("Saving\u2026");
      try {
        const body = buildGenerateChartBody({
          name: this.chartDraft.name,
          date: this.chartDraft.date,
          time: this.chartDraft.time,
          latitude: this.chartDraft.latitude,
          longitude: this.chartDraft.longitude,
          timezone: this.chartDraft.timezone,
          save: true
        });
        await this.plugin.generateChart(body);
        new import_obsidian.Notice(`Saved chart "${body.name}"`);
        this.plugin.settings.selectedChart = body.name;
        await this.plugin.saveSettings();
        this.cachedCharts = null;
        this.display();
      } catch (err) {
        new import_obsidian.Notice(`Save failed: ${(_a = err == null ? void 0 : err.message) != null ? _a : err}`, 8e3);
      } finally {
        btn.setDisabled(false).setButtonText("Save chart");
      }
    }));
  }
  async populateChartDropdown(dropdown) {
    var _a;
    const current = this.plugin.settings.selectedChart;
    dropdown.empty();
    dropdown.createEl("option", { text: "\u2014 None (sky-to-sky aspects) \u2014", value: "" });
    try {
      if (!this.cachedCharts)
        this.cachedCharts = await this.plugin.listSavedCharts();
      for (const name of this.cachedCharts) {
        dropdown.createEl("option", { text: name, value: name });
      }
      dropdown.value = current && this.cachedCharts.includes(current) ? current : "";
    } catch (err) {
      const opt = dropdown.createEl("option", {
        text: `(couldn't load charts: ${(_a = err == null ? void 0 : err.message) != null ? _a : err})`,
        value: ""
      });
      opt.disabled = true;
    }
  }
  async searchLocations(query, container) {
    var _a;
    container.empty();
    const loading = container.createDiv({ cls: "moon-loc-loading", text: "Searching\u2026" });
    try {
      const url = `https://nominatim.openstreetmap.org/search?format=json&limit=5&q=${encodeURIComponent(query)}`;
      const res = await (0, import_obsidian.requestUrl)({
        url,
        headers: { "User-Agent": "obsidian-moon-plugin/1.1 (https://github.com/PoweredbyPugs/moon-phase)" },
        throw: false
      });
      loading.remove();
      if (res.status < 200 || res.status >= 300) {
        container.createDiv({ cls: "moon-loc-error", text: `Geocoding failed: HTTP ${res.status}` });
        return;
      }
      const items = res.json;
      if (!items || items.length === 0) {
        container.createDiv({ cls: "moon-loc-empty", text: "No results." });
        return;
      }
      for (const item of items) {
        const row = container.createDiv({ cls: "moon-loc-row" });
        row.createSpan({ text: item.display_name });
        row.addEventListener("click", () => {
          this.chartDraft.locationName = item.display_name;
          this.chartDraft.latitude = parseFloat(item.lat);
          this.chartDraft.longitude = parseFloat(item.lon);
          this.display();
        });
      }
    } catch (err) {
      loading.remove();
      container.createDiv({ cls: "moon-loc-error", text: `Geocoding failed: ${(_a = err == null ? void 0 : err.message) != null ? _a : err}` });
    }
  }
  /* ── Planets ── */
  renderPlanets(c) {
    c.createEl("p", {
      cls: "moon-tab-intro",
      text: "Toggle which planets appear in position lists and aspect calculations."
    });
    for (const planet of PLANETS) {
      new import_obsidian.Setting(c).setName(`${planetGlyph(planet)} ${planet}`).addToggle((t) => t.setValue(this.plugin.settings.planets[planet]).onChange(async (v) => {
        this.plugin.settings.planets[planet] = v;
        await this.plugin.saveSettings();
      }));
    }
  }
  /* ── Aspects ── */
  renderAspects(c) {
    c.createEl("p", {
      cls: "moon-tab-intro",
      text: "Toggle which aspect types appear in aspect commands. (Orb for sky-to-sky aspects comes from the server; orb for natal transits is set on the Natal Chart tab.)"
    });
    for (const aspect of ASPECTS) {
      new import_obsidian.Setting(c).setName(`${ASPECT_SYMBOLS[aspect]} ${aspect}`).addToggle((t) => t.setValue(this.plugin.settings.aspects[aspect]).onChange(async (v) => {
        this.plugin.settings.aspects[aspect] = v;
        await this.plugin.saveSettings();
      }));
    }
  }
  /* ── Techniques ── */
  renderTechniques(c) {
    c.createEl("p", {
      cls: "moon-tab-intro",
      text: "Toggle additional astrological / divinatory techniques. Disabled techniques are hidden from the command palette. Ki and Hexagram run entirely client-side; midpoints / eclipses / dashas hit the Sweph server."
    });
    new import_obsidian.Setting(c).setName("9 Star Ki").setDesc("Today's Ki cascade (year/month/third) and natal Ki personal-cycle commands. Pure-TS, no server call.").addToggle((t) => t.setValue(this.plugin.settings.techniques.ki).onChange(async (v) => {
      this.plugin.settings.techniques.ki = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(c).setName("Birth date for natal Ki").setDesc("YYYY-MM-DD. Only used when no saved chart is selected. Optional.").addText((t) => t.setPlaceholder("1986-05-01").setValue(this.plugin.settings.birthDate).onChange(async (v) => {
      this.plugin.settings.birthDate = v.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(c).setName("I Ching Hexagram").setDesc("Three-coin cast \u2192 primary hexagram + relating hexagram (if changing lines). Pure-TS.").addToggle((t) => t.setValue(this.plugin.settings.techniques.hexagram).onChange(async (v) => {
      this.plugin.settings.techniques.hexagram = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(c).setName("Midpoints").setDesc("Current transits aspecting natal midpoints. Requires Sweph-server endpoint /midpoint-transits/:name.").addToggle((t) => t.setValue(this.plugin.settings.techniques.midpoints).onChange(async (v) => {
      this.plugin.settings.techniques.midpoints = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(c).setName("Midpoint orb (degrees)").setDesc("Tightness of midpoint-transit aspects. Sent as ?orb=N.").addSlider((s) => s.setLimits(0.5, 5, 0.5).setValue(this.plugin.settings.midpointOrb).setDynamicTooltip().onChange(async (v) => {
      this.plugin.settings.midpointOrb = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(c).setName("Eclipses").setDesc('"Next Eclipse" command. Requires Sweph-server endpoint /eclipses.').addToggle((t) => t.setValue(this.plugin.settings.techniques.eclipses).onChange(async (v) => {
      this.plugin.settings.techniques.eclipses = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(c).setName("Eclipse lookahead (months)").setDesc('How far ahead "Next Eclipse" searches.').addSlider((s) => s.setLimits(1, 24, 1).setValue(this.plugin.settings.eclipseLookaheadMonths).setDynamicTooltip().onChange(async (v) => {
      this.plugin.settings.eclipseLookaheadMonths = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(c).setName("Vimshottari Dashas").setDesc("Vedic dasha periods for a saved chart. Requires Sweph-server endpoint /dashas/:name.").addToggle((t) => t.setValue(this.plugin.settings.techniques.dashas).onChange(async (v) => {
      this.plugin.settings.techniques.dashas = v;
      await this.plugin.saveSettings();
    }));
  }
};
